# Generated by Django 5.2.5 on 2025-08-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_client_delete_assistant_delete_designer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer_data',
            fields=[
                ('office_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('professionalTitle', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('graduationYear', models.CharField(max_length=4)),
                ('technicalSkills', models.JSONField(default=list, help_text='List of technical skills')),
                ('languages', models.JSONField(default=list, help_text='List of languages')),
                ('experience', models.CharField(choices=[('0-1 years', '0-1 years'), ('1-2 years', '1-2 years'), ('2-3 years', '2-3 years'), ('3-5 years', '3-5 years'), ('5+ years', '5+ years'), ('10+ years', '10+ years')], max_length=20)),
                ('Salary', models.CharField(help_text='Salary information', max_length=100)),
                ('availability', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Unavailable', 'Unavailable')], default='Full-time', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Developer Data',
                'verbose_name_plural': 'Developer Data',
                'db_table': 'developer_data',
            },
        ),
    ]
