# Generated by Django 5.2.5 on 2025-08-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_developer_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BD',
            fields=[
                ('BD_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('salary', models.CharField(help_text='Salary information', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('education', models.CharField(help_text='Educational background', max_length=200)),
                ('experience', models.CharField(choices=[('0-1 years', '0-1 years'), ('1-2 years', '1-2 years'), ('2-3 years', '2-3 years'), ('3-5 years', '3-5 years'), ('5+ years', '5+ years'), ('10+ years', '10+ years')], max_length=20)),
                ('availability', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Unavailable', 'Unavailable')], default='Full-time', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Development',
                'verbose_name_plural': 'Business Development',
                'db_table': 'bd_data',
            },
        ),
    ]
