# Generated by Django 5.2.5 on 2025-08-19 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_bd'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship', 'Internship'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=50, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('Entry Level', 'Entry Level'), ('Junior (1-2 years)', 'Junior (1-2 years)'), ('Mid-Level (3-5 years)', 'Mid-Level (3-5 years)'), ('Senior (5+ years)', 'Senior (5+ years)'), ('Lead/Principal', 'Lead/Principal'), ('Executive', 'Executive')], max_length=50, null=True)),
                ('platform', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Indeed', 'Indeed'), ('Glassdoor', 'Glassdoor'), ('AngelList', 'AngelList'), ('Stack Overflow Jobs', 'Stack Overflow Jobs'), ('GitHub Jobs', 'GitHub Jobs'), ('Company Website', 'Company Website'), ('Referral', 'Referral'), ('Other', 'Other')], max_length=50)),
                ('job_url', models.URLField(blank=True, null=True)),
                ('skills', models.JSONField(default=list, help_text='List of required skills')),
                ('job_description', models.TextField(blank=True, null=True)),
                ('key_requirements', models.TextField(blank=True, null=True)),
                ('personal_notes', models.TextField(blank=True, null=True)),
                ('application_status', models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Interview Completed', 'Interview Completed'), ('Offer Received', 'Offer Received'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Accepted', 'Accepted')], default='Applied', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('bd_id', models.ForeignKey(db_column='bd_id', on_delete=django.db.models.deletion.CASCADE, to='authapp.bd')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
