# Generated by Django 5.2.5 on 2025-08-20 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=150)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('company_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bd_id', models.ForeignKey(db_column='bd_id', on_delete=django.db.models.deletion.CASCADE, to='authapp.bd')),
                ('dev_id', models.ForeignKey(db_column='dev_id', on_delete=django.db.models.deletion.CASCADE, to='authapp.developer_data')),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='authapp.jobapplication')),
            ],
            options={
                'db_table': 'interview_schedules',
                'ordering': ['-created_at'],
            },
        ),
    ]
